### PR TITLE
chore: update afj to 0.3.3

### PR DESCRIPTION
**Pull request by TimoGlastra**
Updates AFJ to latest version, mainly so we can use the new `connectionTypes` property on the connection record.

Also added `autoUpdateStorageOnStartup` so in the future agents can update automatically to new versions of AFJ

### CODE REVIEW

**Review by blu3beri — APPROVED** [review]
LGTM! @Tommylans is there a reason why we were on the beta version of a lot of the `@electron-force` dependencies? Would this break anything in the release?

**Comment by TimoGlastra** [comment]
I think it wasn't out yet. I talked about this with @Tommylans and he said we can't update eletron yet due to some v8 sandboxing issues with indy-sdk, but these should be fine.

But would be good to verify that one more time before we merge

**Comment by Tommylans** [comment]
These were the versions that came with the forge project setup. So I think they just wanted to push everyone that had a new project to use the new v6 version. :+1:

**Comment by Tommylans** [comment]
@blu3beri Oh I also think nothing will break with the release because the hooks etc are still the same.

**Review by Tommylans — APPROVED** [review]

**Pull request merged**
